use sdl3_sys::everything as sdl;

pub(crate) fn key_name(key: sdl::SDL_Keycode) -> Option<String> {
    let named = match key {
        sdl::SDLK_LEFT => "left",
        sdl::SDLK_RIGHT => "right",
        sdl::SDLK_UP => "up",
        sdl::SDLK_DOWN => "down",
        sdl::SDLK_HOME => "home",
        sdl::SDLK_END => "end",
        sdl::SDLK_PAGEUP => "pageup",
        sdl::SDLK_PAGEDOWN => "pagedown",
        sdl::SDLK_INSERT => "insert",
        sdl::SDLK_DELETE => "delete",
        sdl::SDLK_ESCAPE => "escape",
        sdl::SDLK_TAB => "tab",
        sdl::SDLK_BACKSPACE => "backspace",
        sdl::SDLK_RETURN | sdl::SDLK_KP_ENTER => "enter",
        sdl::SDLK_SPACE => "space",
        sdl::SDLK_F1 => "f1",
        sdl::SDLK_F2 => "f2",
        sdl::SDLK_F3 => "f3",
        sdl::SDLK_F4 => "f4",
        sdl::SDLK_F5 => "f5",
        sdl::SDLK_F6 => "f6",
        sdl::SDLK_F7 => "f7",
        sdl::SDLK_F8 => "f8",
        sdl::SDLK_F9 => "f9",
        sdl::SDLK_F10 => "f10",
        sdl::SDLK_F11 => "f11",
        sdl::SDLK_F12 => "f12",
        sdl::SDLK_F13 => "f13",
        sdl::SDLK_F14 => "f14",
        sdl::SDLK_F15 => "f15",
        sdl::SDLK_F16 => "f16",
        sdl::SDLK_F17 => "f17",
        sdl::SDLK_F18 => "f18",
        sdl::SDLK_F19 => "f19",
        sdl::SDLK_F20 => "f20",
        sdl::SDLK_F21 => "f21",
        sdl::SDLK_F22 => "f22",
        sdl::SDLK_F23 => "f23",
        sdl::SDLK_F24 => "f24",
        sdl::SDLK_PRINTSCREEN => "printscreen",
        sdl::SDLK_SCROLLLOCK => "scrolllock",
        sdl::SDLK_PAUSE => "pause",
        sdl::SDLK_NUMLOCKCLEAR => "numlock",
        sdl::SDLK_CAPSLOCK => "capslock",
        sdl::SDLK_KP_0 => "0",
        sdl::SDLK_KP_1 => "1",
        sdl::SDLK_KP_2 => "2",
        sdl::SDLK_KP_3 => "3",
        sdl::SDLK_KP_4 => "4",
        sdl::SDLK_KP_5 => "5",
        sdl::SDLK_KP_6 => "6",
        sdl::SDLK_KP_7 => "7",
        sdl::SDLK_KP_8 => "8",
        sdl::SDLK_KP_9 => "9",
        sdl::SDLK_KP_PLUS => "+",
        sdl::SDLK_KP_MINUS => "-",
        sdl::SDLK_KP_MULTIPLY => "*",
        sdl::SDLK_KP_DIVIDE => "/",
        sdl::SDLK_KP_PERIOD | sdl::SDLK_KP_DECIMAL => ".",
        sdl::SDLK_KP_EQUALS | sdl::SDLK_KP_EQUALSAS400 => "=",
        sdl::SDLK_KP_COMMA => ",",
        sdl::SDLK_KP_00 => "00",
        sdl::SDLK_KP_000 => "000",
        sdl::SDLK_KP_LEFTPAREN => "(",
        sdl::SDLK_KP_RIGHTPAREN => ")",
        sdl::SDLK_KP_LEFTBRACE => "{",
        sdl::SDLK_KP_RIGHTBRACE => "}",
        sdl::SDLK_KP_TAB => "tab",
        sdl::SDLK_KP_BACKSPACE => "backspace",
        sdl::SDLK_KP_A => "a",
        sdl::SDLK_KP_B => "b",
        sdl::SDLK_KP_C => "c",
        sdl::SDLK_KP_D => "d",
        sdl::SDLK_KP_E => "e",
        sdl::SDLK_KP_F => "f",
        sdl::SDLK_KP_XOR => "xor",
        sdl::SDLK_KP_POWER => "^",
        sdl::SDLK_KP_PERCENT => "%",
        sdl::SDLK_KP_LESS => "<",
        sdl::SDLK_KP_GREATER => ">",
        sdl::SDLK_KP_AMPERSAND => "&",
        sdl::SDLK_KP_DBLAMPERSAND => "&&",
        sdl::SDLK_KP_VERTICALBAR => "|",
        sdl::SDLK_KP_DBLVERTICALBAR => "||",
        sdl::SDLK_KP_COLON => ":",
        sdl::SDLK_KP_HASH => "#",
        sdl::SDLK_KP_SPACE => "space",
        sdl::SDLK_KP_AT => "@",
        sdl::SDLK_KP_EXCLAM => "!",
        sdl::SDLK_KP_MEMSTORE => "memstore",
        sdl::SDLK_KP_MEMRECALL => "memrecall",
        sdl::SDLK_KP_MEMCLEAR => "memclear",
        sdl::SDLK_KP_MEMADD => "memadd",
        sdl::SDLK_KP_MEMSUBTRACT => "memsubtract",
        sdl::SDLK_KP_MEMMULTIPLY => "memmultiply",
        sdl::SDLK_KP_MEMDIVIDE => "memdivide",
        sdl::SDLK_KP_PLUSMINUS => "+-",
        sdl::SDLK_KP_CLEAR => "clear",
        sdl::SDLK_KP_CLEARENTRY => "clearentry",
        sdl::SDLK_KP_BINARY => "binary",
        sdl::SDLK_KP_OCTAL => "octal",
        sdl::SDLK_KP_HEXADECIMAL => "hexadecimal",
        sdl::SDLK_APPLICATION | sdl::SDLK_MENU => "menu",
        sdl::SDLK_POWER => "power",
        sdl::SDLK_EXECUTE => "execute",
        sdl::SDLK_HELP => "help",
        sdl::SDLK_SELECT => "select",
        sdl::SDLK_STOP => "stop",
        sdl::SDLK_AGAIN => "again",
        sdl::SDLK_UNDO => "undo",
        sdl::SDLK_CUT => "cut",
        sdl::SDLK_COPY => "copy",
        sdl::SDLK_PASTE => "paste",
        sdl::SDLK_FIND => "find",
        sdl::SDLK_MUTE => "mute",
        sdl::SDLK_VOLUMEUP => "volumeup",
        sdl::SDLK_VOLUMEDOWN => "volumedown",
        sdl::SDLK_ALTERASE => "alterase",
        sdl::SDLK_SYSREQ => "sysreq",
        sdl::SDLK_CANCEL => "cancel",
        sdl::SDLK_CLEAR => "clear",
        sdl::SDLK_PRIOR => "prior",
        sdl::SDLK_RETURN2 => "enter",
        sdl::SDLK_SEPARATOR => "separator",
        sdl::SDLK_OUT => "out",
        sdl::SDLK_OPER => "oper",
        sdl::SDLK_CLEARAGAIN => "clearagain",
        sdl::SDLK_CRSEL => "crsel",
        sdl::SDLK_EXSEL => "exsel",
        sdl::SDLK_THOUSANDSSEPARATOR => "thousandsseparator",
        sdl::SDLK_DECIMALSEPARATOR => "decimalseparator",
        sdl::SDLK_CURRENCYUNIT => "currencyunit",
        sdl::SDLK_CURRENCYSUBUNIT => "currencysubunit",
        sdl::SDLK_LCTRL | sdl::SDLK_RCTRL => "control",
        sdl::SDLK_LALT | sdl::SDLK_RALT => "alt",
        sdl::SDLK_LSHIFT | sdl::SDLK_RSHIFT => "shift",
        sdl::SDLK_LGUI | sdl::SDLK_RGUI => "platform",
        sdl::SDLK_MODE => "mode",
        sdl::SDLK_SLEEP => "sleep",
        sdl::SDLK_WAKE => "wake",
        sdl::SDLK_CHANNEL_INCREMENT => "channelincrement",
        sdl::SDLK_CHANNEL_DECREMENT => "channeldecrement",
        sdl::SDLK_MEDIA_PLAY => "mediaplay",
        sdl::SDLK_MEDIA_PAUSE => "mediapause",
        sdl::SDLK_MEDIA_RECORD => "mediarecord",
        sdl::SDLK_MEDIA_FAST_FORWARD => "mediafastforward",
        sdl::SDLK_MEDIA_REWIND => "mediarewind",
        sdl::SDLK_MEDIA_NEXT_TRACK => "medianexttrack",
        sdl::SDLK_MEDIA_PREVIOUS_TRACK => "mediaprevioustrack",
        sdl::SDLK_MEDIA_STOP => "mediastop",
        sdl::SDLK_MEDIA_EJECT => "mediaeject",
        sdl::SDLK_MEDIA_PLAY_PAUSE => "mediaplaypause",
        sdl::SDLK_MEDIA_SELECT => "mediaselect",
        sdl::SDLK_AC_NEW => "new",
        sdl::SDLK_AC_OPEN => "open",
        sdl::SDLK_AC_CLOSE => "close",
        sdl::SDLK_AC_EXIT => "exit",
        sdl::SDLK_AC_SAVE => "save",
        sdl::SDLK_AC_PRINT => "print",
        sdl::SDLK_AC_PROPERTIES => "properties",
        sdl::SDLK_AC_SEARCH => "search",
        sdl::SDLK_AC_HOME => "browserhome",
        sdl::SDLK_AC_BACK => "back",
        sdl::SDLK_AC_FORWARD => "forward",
        sdl::SDLK_AC_STOP => "browserstop",
        sdl::SDLK_AC_REFRESH => "refresh",
        sdl::SDLK_AC_BOOKMARKS => "bookmarks",
        sdl::SDLK_SOFTLEFT => "softleft",
        sdl::SDLK_SOFTRIGHT => "softright",
        sdl::SDLK_CALL => "call",
        sdl::SDLK_ENDCALL => "endcall",
        sdl::SDLK_LEFT_TAB => "tab",
        sdl::SDLK_LEVEL5_SHIFT => "level5shift",
        sdl::SDLK_MULTI_KEY_COMPOSE => "compose",
        sdl::SDLK_LMETA | sdl::SDLK_RMETA => "meta",
        sdl::SDLK_LHYPER | sdl::SDLK_RHYPER => "hyper",
        _ => return printable_key(key),
    };
    Some(named.to_owned())
}

pub(crate) fn modifiers(raw: sdl::SDL_Keymod) -> (gpui::Modifiers, gpui::Capslock) {
    (
        gpui::Modifiers {
            control: raw.0 & sdl::SDL_KMOD_CTRL.0 != 0,
            alt: raw.0 & sdl::SDL_KMOD_ALT.0 != 0,
            shift: raw.0 & sdl::SDL_KMOD_SHIFT.0 != 0,
            platform: raw.0 & sdl::SDL_KMOD_GUI.0 != 0,
            function: false,
        },
        gpui::Capslock {
            on: raw.0 & sdl::SDL_KMOD_CAPS.0 != 0,
        },
    )
}

fn printable_key(key: sdl::SDL_Keycode) -> Option<String> {
    let character = char::from_u32(key.0)?;
    (!character.is_control() && !character.is_whitespace())
        .then(|| character.to_lowercase().collect())
}
